# Python basic Assignment 8

## 1. Write a Python Program to Add Two Matrices?

In [1]:
mat1 = [[1,6,4],
        [4,5,6],
        [7,6,9]]

mat2 = [[2,5,4],
        [5,8,7],
        [8,3,1]]

sumMat = [[0,0,0],
          [0,0,0],
          [0,0,0]]

sumMat = [[mat1[i][j] + mat2[i][j] for j in range(len(mat1[0]))] for i in range(len(mat2))]
print("The Sum of two matrix {}  and {}  is \n{} ".format(mat1,mat2,sumMat))

The Sum of two matrix [[1, 6, 4], [4, 5, 6], [7, 6, 9]]  and [[2, 5, 4], [5, 8, 7], [8, 3, 1]]  is 
[[3, 11, 8], [9, 13, 13], [15, 9, 10]] 


In [2]:
# solution 2
import numpy as np

mat1 = np.array([[1,6,4],
        [4,5,6],
        [7,6,9]])
mat2 = np.array([[2,5,4],
        [5,8,7],
        [8,3,1]])

sumMat = np.add(mat1,mat2)
print("The Sum of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,sumMat))

The Sum of two matrix 

[[1 6 4]
 [4 5 6]
 [7 6 9]]  and 

[[2 5 4]
 [5 8 7]
 [8 3 1]]  is 

[[ 3 11  8]
 [ 9 13 13]
 [15  9 10]] 


## 2. Write a Python Program to Multiply Two Matrices?

In [1]:
a = [[1,2,3],[4,5,6],[7,8,9]]
b = [[1,4,7],[2,5,8],[3,6,9]]

def multiply_matrice(a,b):
    output = []
    if len(a[0]) == len(b):
        for ele in range(len(a[0])):
            output.append([0 for ele in range(len(b[0]))])
        for i in range(len(a)):
            for j in range(len(b[0])):
                for k in range(len(b)):
                    output[i][j] += a[i][k]*b[k][j]
        print(output)     
    else:
        print('Matrix Multiplication is Not Possible')
        
multiply_matrice(a,b)

[[14, 32, 50], [32, 77, 122], [50, 122, 194]]


In [2]:
# solution 2
import numpy as np

mat1 = np.array([[1,2,4],
        [4,5,6],
        [7,8,9]])
mat2 = np.array([[2,3,4],
        [5,6,7],
        [8,9,1]])

sumMat = np.dot(mat1,mat2)
print("The product of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,sumMat))

The product of two matrix 

[[1 2 4]
 [4 5 6]
 [7 8 9]]  and 

[[2 3 4]
 [5 6 7]
 [8 9 1]]  is 

[[ 44  51  22]
 [ 81  96  57]
 [126 150  93]] 


## 3. Write a Python Program to transpose a Matrix ?

In [1]:
def initializeMatrix(n,v=0):
    M=[]             
    for i in range(n):
        #stor row
        row =[]
        for j in range(n):
            row.append(v)
        M.append(row)
    return(M)

def createMatrix(n):
    
    M=[]             
    print("Enter the element :")
    for i in range(n):
        #stor row
        row =[]
        for j in range(n):
            row.append(int(input()))
        M.append(row)
    return(M)

def printMatrix(M,n):
    for i in range(n):
        for j in range(n):
            print(M[i][j], end=" ")
        print() 
        
def transposeMatrix(M,n,result):
    for i in range(n):
        for j in range(n):
            result[i][j]= M[j][i]
    return result

n=int(input("Enter N for N x N matrix: "))       
M1 = createMatrix(n)
#Display the 2D array
print("Display Array M1 In Matrix Form")
printMatrix(M1,n)

result = initializeMatrix(n)
result = transposeMatrix(M1,n,result)
print("Transposed Matrix")
for r in result:
    print(r)

Enter N for N x N matrix: 3
Enter the element :
153
426
157
359
759
153
953
751
852
Display Array M1 In Matrix Form
153 426 157 
359 759 153 
953 751 852 
Transposed Matrix
[153, 359, 953]
[426, 759, 751]
[157, 153, 852]


In [5]:
#solution 2
a = [[1,2,3],[4,5,6],[7,8,9]]
b = [[1,2],[4,5],[7,8]]
c = [[1,2,3],[4,5,6]]

def generate_transpose(in_matrix):
    out_matrix = []
    for ele in range(len(in_matrix[0])):
        out_matrix.append([0 for i in range(len(in_matrix))])
    for i in range(len(in_matrix)):
        for j in range(len(in_matrix[i])):
            out_matrix[j][i] = in_matrix[i][j]
    print(f'{in_matrix} ---> {out_matrix}')
        
generate_transpose(a)
generate_transpose(b)
generate_transpose(c)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]] ---> [[1, 4, 7], [2, 5, 8], [3, 6, 9]]
[[1, 2], [4, 5], [7, 8]] ---> [[1, 4, 7], [2, 5, 8]]
[[1, 2, 3], [4, 5, 6]] ---> [[1, 4], [2, 5], [3, 6]]


## 4. Write a Python Program to sort Words in an Alphabatical Order ?

In [6]:
str = input("Enter some string : ")

words = str.split()
words.sort()
for word in words:
    print(word)

Enter some string : my name is rani vaishnav
is
my
name
rani
vaishnav


In [1]:
#solution 2
def sortString():
    in_string = input("Enter a String: ").title()
    sorted_list = sorted(in_string.split())
    print(' '.join(sorted_list))

sortString()

Enter a String: hey hi this is rani vaishnav
Hey Hi Is Rani This Vaishnav


## 5. Write a Python Program to remove Punctuations From a String ?

In [2]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

str = input("Enter some string with panctuations")

# remove punctuation from the string
no_punct = ""
for char in str:
    if char not in punctuations:
        no_punct = no_punct + char

# display the unpunctuated string
print(no_punct)

Enter some string with panctuations( hello ) - ra$ni vaish@nav is # here& * 
 hello   rani vaishnav is  here  
